# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/kanban
spring.datasource.username=postgres

spring.datasource.password=Chinni@1806
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
# update: automatically updates the database table structure when our Java models change
spring.jpa.hibernate.ddl-auto=update
# show-sql: prints the raw SQL queries to the console so we can see what Hibernate is doing
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect